import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useLocation } from "wouter";

export default function PrivacyPolicy() {
  const [, setLocation] = useLocation();

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-gradient-to-r from-primary to-secondary py-8 px-4">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center space-x-3 mb-4">
            <img
              src="https://trackwala.com/brand-avatar.png"
              alt="TrackWala"
              className="w-12 h-12 rounded-full"
            />
            <h1 className="text-3xl font-bold text-white">TrackWala</h1>
          </div>
          <h2 className="text-2xl font-bold text-white">Privacy Policy</h2>
          <p className="text-white/90 mt-2">Last Updated: January 2025</p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-12">
        <Card className="p-8">
          <div className="prose prose-gray max-w-none">
            <section className="mb-8">
              <h3 className="text-xl font-bold mb-4">1. Introduction</h3>
              <p className="text-gray-700 mb-4">
                TrackWala ("we," "our," or "us") operates a vehicle buyout
                service. This Privacy Policy explains how we collect, use,
                disclose, and protect your information when you use our
                services.
              </p>
              <p className="text-gray-700">
                By using our services, you agree to the collection and use of
                information in accordance with this policy.
              </p>
            </section>

            <section className="mb-8">
              <h3 className="text-xl font-bold mb-4">
                2. Information We Collect
              </h3>
              <p className="text-gray-700 mb-4">
                We collect the following types of information:
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>
                  Vehicle Information: VIN, make, model, year, mileage,
                  condition, title status
                </li>
                <li>Contact Information: Name, email address, phone number</li>
                <li>Vehicle Photos: Images you upload of your vehicle</li>
                <li>Location Data: City and state for pickup arrangements</li>
                <li>
                  Usage Data: IP address, browser type, pages visited, time
                  spent on site
                </li>
              </ul>
            </section>

            <section className="mb-8">
              <h3 className="text-xl font-bold mb-4">
                3. How We Use Your Information
              </h3>
              <p className="text-gray-700 mb-4">
                We use the collected information for:
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>Providing and maintaining our vehicle buyout services</li>
                <li>Generating cash offers for your vehicle</li>
                <li>
                  Communicating with you about offers, pickups, and transactions
                </li>
                <li>Processing payments and completing vehicle purchases</li>
                <li>Improving our services and user experience</li>
                <li>Preventing fraud and ensuring security</li>
                <li>Complying with legal obligations</li>
              </ul>
            </section>

            <section className="mb-8">
              <h3 className="text-xl font-bold mb-4">
                4. Offers and Intellectual Property
              </h3>

              <p className="text-gray-700 mb-4">
                <strong>IMPORTANT:</strong> All offers generated by TrackWala
                are:
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>
                  Non-binding estimates subject to vehicle inspection and
                  verification
                </li>
                <li>
                  Valid for 7 days from the date of issue unless otherwise
                  specified
                </li>
                <li>
                  Subject to change based on actual vehicle condition, market
                  conditions, or errors in submitted information
                </li>
                <li>
                  Proprietary to TrackWala and protected as trade secrets and
                  confidential business information
                </li>
              </ul>

              <p className="text-gray-700 mb-4">
                Our pricing algorithms, valuation methods, and offer
                calculations constitute proprietary intellectual property. You
                agree not to:
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>
                  Reverse engineer, decompile, or attempt to derive our pricing
                  methodology
                </li>
                <li>
                  Use our offers for competitive analysis or to develop
                  competing services
                </li>
                <li>
                  Share, publish, or disclose offer details with third parties
                  for commercial purposes
                </li>
                <li>
                  Submit false or misleading information to manipulate offer
                  amounts
                </li>
              </ul>
            </section>

            <section className="mb-8">
              <h3 className="text-xl font-bold mb-4">
                5. Title Transfer and Power of Attorney
              </h3>

              <p className="text-gray-700 mb-4">
                <strong>IMPORTANT - Title Transfer Requirements:</strong>
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>
                  Transfer of vehicle ownership and title is NOT guaranteed without a properly executed Power of Attorney (POA)
                </li>
                <li>
                  You may be required to provide a signed POA authorizing TrackWala to handle title transfer and registration on your behalf
                </li>
                <li>
                  All POA documents must be notarized and comply with state-specific requirements
                </li>
                <li>
                  We cannot complete the vehicle purchase or transfer title without proper legal documentation
                </li>
                <li>
                  You are responsible for ensuring all title transfer documents are accurate, complete, and legally valid
                </li>
                <li>
                  TrackWala is not liable for any delays, fees, or complications arising from incomplete or improper POA documentation
                </li>
              </ul>

              <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mt-4">
                <p className="text-amber-900 font-medium">
                  ⚠️ Without a valid POA, you may need to appear in person for title transfer, which could delay or prevent the completion of your vehicle sale.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h3 className="text-xl font-bold mb-4">
                6. Right to Refuse Service
              </h3>

              <p className="text-gray-700 mb-4">
                <strong>TrackWala reserves the absolute right to:</strong>
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>Refuse service to anyone for any reason at any time</li>
                <li>
                  Cancel, modify, or withdraw any offer at our sole discretion
                </li>
                <li>
                  Decline to purchase any vehicle, even after an offer has been
                  made
                </li>
                <li>Terminate user accounts or block access to our services</li>
                <li>
                  Reject submissions containing false, misleading, or incomplete
                  information
                </li>
              </ul>

              <p className="text-gray-700">
                No offer is final or binding until a purchase agreement is
                signed by both parties and payment is completed. We may cancel
                any transaction prior to final completion if we discover:
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2 mt-2">
                <li>
                  Discrepancies in vehicle condition or information provided
                </li>
                <li>Title issues or ownership disputes</li>
                <li>Suspected fraud or misrepresentation</li>
                <li>Legal or regulatory concerns</li>
                <li>Changes in market conditions affecting vehicle value</li>
              </ul>
            </section>

            <section className="mb-8">
              <h3 className="text-xl font-bold mb-4">
                7. Limitation of Liability
              </h3>
              <p className="text-gray-700 mb-4">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW:
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>
                  TrackWala shall not be liable for any indirect, incidental,
                  special, consequential, or punitive damages
                </li>
                <li>
                  You agree not to sue TrackWala, its affiliates, officers,
                  directors, employees, or agents regarding offers, valuations,
                  or business decisions
                </li>
                <li>
                  Our total liability for any claims shall not exceed the amount
                  of the offer in question
                </li>
                <li>
                  All offers are provided "AS IS" without warranties of any kind
                </li>
                <li>
                  We are not responsible for errors in third-party vehicle data
                  or pricing information
                </li>
              </ul>
            </section>

            <section className="mb-8">
              <h3 className="text-xl font-bold mb-4">8. Data Security</h3>
              <p className="text-gray-700 mb-4">
                We implement reasonable security measures to protect your
                information, including:
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>Encrypted data transmission (SSL/TLS)</li>
                <li>Secure server infrastructure</li>
                <li>Access controls and authentication</li>
                <li>Regular security audits</li>
              </ul>
              <p className="text-gray-700 mt-4">
                However, no method of transmission over the Internet is 100%
                secure. We cannot guarantee absolute security of your
                information.
              </p>
            </section>

            <section className="mb-8">
              <h3 className="text-xl font-bold mb-4">9. Information Sharing</h3>
              <p className="text-gray-700 mb-4">
                We may share your information with:
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>
                  Service providers who assist in our operations (payment
                  processors, vehicle inspectors)
                </li>
                <li>
                  Law enforcement or government agencies when required by law
                </li>
                <li>
                  Business partners in connection with vehicle sales or
                  transfers
                </li>
                <li>Third parties with your explicit consent</li>
              </ul>
              <p className="text-gray-700 mt-4">
                We do not sell your personal information to third parties for
                marketing purposes.
              </p>
            </section>

            <section className="mb-8">
              <h3 className="text-xl font-bold mb-4">10. Your Rights</h3>
              <p className="text-gray-700 mb-4">You have the right to:</p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>Access the personal information we hold about you</li>
                <li>Request correction of inaccurate information</li>
                <li>
                  Request deletion of your information (subject to legal
                  retention requirements)
                </li>
                <li>Opt-out of marketing communications</li>
                <li>Withdraw consent for data processing where applicable</li>
              </ul>
            </section>

            <section className="mb-8">
              <h3 className="text-xl font-bold mb-4">
                11. Cookies and Tracking
              </h3>
              <p className="text-gray-700 mb-4">
                We use cookies and similar tracking technologies to improve user
                experience and analyze usage patterns. You can control cookie
                settings through your browser preferences.
              </p>
            </section>

            <section className="mb-8">
              <h3 className="text-xl font-bold mb-4">12. Third-Party Links</h3>
              <p className="text-gray-700">
                Our service may contain links to third-party websites. We are
                not responsible for the privacy practices or content of these
                external sites.
              </p>
            </section>

            <section className="mb-8">
              <h3 className="text-xl font-bold mb-4">13. Children's Privacy</h3>
              <p className="text-gray-700">
                Our services are not intended for individuals under 18 years of
                age. We do not knowingly collect information from children.
              </p>
            </section>

            <section className="mb-8">
              <h3 className="text-xl font-bold mb-4">
                14. Changes to This Policy
              </h3>
              <p className="text-gray-700">
                We may update this Privacy Policy periodically. Changes will be
                posted on this page with an updated "Last Updated" date.
                Continued use of our services after changes constitutes
                acceptance of the revised policy.
              </p>
            </section>

            <section className="mb-8">
              <h3 className="text-xl font-bold mb-4">
                15. Dispute Resolution and Arbitration
              </h3>
              <p className="text-gray-700 mb-4">
                Any disputes arising from or relating to our services shall be
                resolved through binding arbitration rather than in court. You
                agree to waive your right to participate in class action
                lawsuits.
              </p>
            </section>

            <section className="mb-8">
              <h3 className="text-xl font-bold mb-4">16. Contact Us</h3>
              <p className="text-gray-700 mb-4">
                If you have questions about this Privacy Policy or wish to
                exercise your rights, please contact us:
              </p>
              <div className="bg-gray-50 rounded-lg p-4">
                <p className="text-gray-700">
                  <strong>TrackWala</strong>
                  <br />
                  Email: support@trackwala.com
                </p>
              </div>
            </section>

            <section>
              <h3 className="text-xl font-bold mb-4">
                17. Acceptance of Terms
              </h3>
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <p className="text-gray-700">
                  By using TrackWala's services, you acknowledge that you have
                  read, understood, and agree to be bound by this Privacy Policy
                  and all terms contained herein, including our right to refuse
                  service and limitations on liability.
                </p>
              </div>
            </section>
          </div>
        </Card>

        <div className="mt-8 text-center">
          <Button
            onClick={() => setLocation("/")}
            size="lg"
            className="bg-primary hover:bg-primary/90"
          >
            Return to Home
          </Button>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-gray-800 text-white py-8 px-4 mt-12">
        <div className="max-w-6xl mx-auto text-center">
          <div className="flex items-center justify-center space-x-3 mb-4">
            <img
              src="/brand-avatar.png"
              alt="TrackWala"
              className="w-12 h-12 rounded-full"
            />
            <span className="text-lg font-semibold">TrackWala</span>
          </div>
          <p className="text-sm text-gray-400">
            Fast, fair, and hassle-free vehicle buyouts
          </p>
        </div>
      </footer>
    </div>
  );
}
